#pragma config(Sensor, dgtl1,  Sonar,          sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int sonarV

while(true){
sonarV = SensorValue[Sonar];
}
}
