#pragma config(Sensor, dgtl1,  Limit1,         sensorTouch)
#pragma config(Sensor, dgtl2,  Limit2,         sensorTouch)
#pragma config(Sensor, dgtl3,  Limit3,         sensorTouch)
#pragma config(Sensor, dgtl4,  Limit4,         sensorTouch)
#pragma config(Motor,  port1,           Right,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          Left,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(Limit1)==0 && SensorValue(Limit2)==0 &&SensorValue(Limit3)==0 &&SensorValue(Limit4)==0){
		motor[Right] = vexRT[Ch2];
		motor[Left] = vexRT[Ch3];
	}
}
